conky.config = {
  background = true,
  double_buffer = true,
  own_window = true,
  own_window_type = 'desktop',
  update_interval = 1.0,
  use_xft = true,

  alignment = "top_left",
  font = "Sarasa Term J:size=12",
  font0 = "Sarasa Term J:size=12:style=bold",
  font1 = "Source Sans 3:size=36:style=bold",
  own_window_argb_value = 250,
  own_window_argb_visual = true,
  own_window_transparent = false,
  draw_shades = true,
  border_inner_margin = 16,
  border_outer_margin = 0,
  border_width = 0,
  gap_x = 8 + 16,
  gap_y = 50 + 16,

  own_window_colour = "#151515",
  default_shade_color = "#151515",
  default_color = "#d8d0d5",
  color0 = "909090",
  color1 = "ee9598",
  color2 = "e8b197",
  color3 = "e8d097",
  color4 = "9be099",
  color5 = "97d0e8",
  color6 = "979ae8",
  color7 = "ca97e8",
  color8 = "ee95d2",

  cpu_avg_samples = 2,
  net_avg_samples = 2,
  no_buffers = true,

  out_to_console = false,
  out_to_ncurses = false,
  out_to_stderr = false,
  out_to_x = true,
}
