#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x polybar >/dev/null || polybar cat -q &
fcitx5 -d

(sleep 5 && [ -f ~/.xkeymap ] && xkbcomp ~/.xkeymap $DISPLAY)&

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.625

bspc config normal_border_color  "#151515"
bspc config active_border_color  "#151515"
bspc config focused_border_color "#d895ee"

bspc rule -a "layer=above" "border=off"

bspc rule -a firefox             "desktop=^2"
bspc rule -a org.squidowl.halloy "desktop=^3"
bspc rule -a VencordDesktop      "desktop=^3"
bspc rule -a cantata             "desktop=^4"
bspc rule -a thunderbird         "desktop=^4"

bspc desktop "^3" -l monocle
bspc desktop "^4" -l monocle
