#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x polybar >/dev/null || polybar cat -q &
fcitx5 -d

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.625

bspc config normal_border_color  "#202020"
bspc config active_border_color  "#202020"
bspc config focused_border_color "#8595ac"

bspc rule -a "layer=above" "border=off"
