[colors.primary]
background = "#121212"
foreground = "#d8d0d5"

[colors.bright]
black   = "#909090"
blue    = "#979ae8"
cyan    = "#97d0e8"
green   = "#9be099"
magenta = "#ca97e8"
red     = "#ee9598"
white   = "#ee95d2"
yellow  = "#e8d097"

[colors.normal]
black   = "#404040"
blue    = "#979ae8"
cyan    = "#97d0e8"
green   = "#9be099"
magenta = "#ca97e8"
red     = "#ee9598"
white   = "#fcf0f8"
yellow  = "#e8d097"

[colors.dim]
black = "#181818"
